apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ CI_COMMIT_REF_NAME }}-app
spec:
  selector:
    matchLabels:
      app: {{ CI_COMMIT_REF_NAME }}-app
  template:
    metadata:
      labels:
        app: {{ CI_COMMIT_REF_NAME }}-app
    spec:
      imagePullSecrets:
      - name: gitlab-registry-{{ CI_PROJECT_ID }}
      containers:
      - name: app
        image: {{ CI_REGISTRY_IMAGE }}/app-{{ CI_COMMIT_REF_NAME }}:latest
        ports:
        - containerPort: 8501
        env:
        - name: LLM_BASE_URL
          value: "https://models.mylab.th-luebeck.dev/v1"
        - name: LLM_MODEL
          value: "llama-3.3-70b-versatile"
        - name: LLM_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ CI_COMMIT_REF_NAME }}-secrets
              key: LLM_API_KEY
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ CI_COMMIT_REF_NAME }}-secrets
type: Opaque
stringData:
  LLM_API_KEY: "{{ LLM_API_KEY }}"